/*
 * Rhyme Kingdom: level definitions.
 *
 * board chars:  .  random tile        -  hole (not part of the board)
 *               R O Y G B P  preset tile (mic, sneaker, chain, cap, headphones, cassette)
 *               1 2 3  record crate with that many layers
 *               S  static (spreads when `spread` is on)
 *               C  crown        K  boss cell
 *               h v x p d  preset power-up (spray row, spray column, boombox, flyer, platinum)
 * floor:        1 / 2  dance-floor layers under the tile
 * tape:         x  the tile is taped in place
 * goals:        { type: color|crate|floor|tape|static|crown|boss, color?, count? }
 *               count is optional for board obstacles (defaults to everything on the board)
 * tutorial:     forced moves at the start of the level, with an optional expected power-up
 */
(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.RKLevels = api;
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const LEVELS = [
    // ---------------- Chapter 1: The Block Party ----------------
    {
      id: 1, name: 'First Beat', moves: 15, colors: [0, 2, 3, 4],
      goals: [{ type: 'color', color: 0, count: 30 }],
      board: [
        '.......',
        '...G...',
        '..GRY..',
        '..RBR..',
        '.......',
        '.......',
        '.......',
      ],
      tutorial: [
        { do: 'swap', a: { c: 3, r: 2 }, b: { c: 3, r: 3 }, text: 'Swipe the mic down to line up 3 in a row.' },
      ],
    },
    {
      id: 2, name: 'Spray It Loud', moves: 18, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'color', color: 4, count: 24 }, { type: 'color', color: 3, count: 24 }],
      board: [
        '........',
        '........',
        '....G...',
        '...GBR..',
        '.RBBYBG.',
        '........',
        '........',
        '........',
      ],
      intro: 'spray',
      tutorial: [
        { do: 'swap', a: { c: 4, r: 3 }, b: { c: 4, r: 4 }, expect: { pw: 'h', c: 4, r: 4 }, text: 'Line up 4 headphones to make a Spray Can.' },
        { do: 'tap', at: { c: 4, r: 4 }, text: 'Tap the Spray Can to tag the whole row.' },
      ],
    },
    {
      id: 3, name: 'Light the Floor', moves: 20, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'floor' }],
      intro: 'floor',
      board: [
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
      ],
      floor: [
        '11111111',
        '1......1',
        '1.1111.1',
        '1.1..1.1',
        '1.1..1.1',
        '1.1111.1',
        '1......1',
        '11111111',
      ],
    },
    {
      id: 4, name: 'Drop the Bass', moves: 17, colors: [0, 1, 2, 3, 5],
      goals: [{ type: 'floor' }, { type: 'color', color: 2, count: 26 }],
      intro: 'boombox',
      board: [
        '-......-',
        '........',
        '....G...',
        '....P...',
        '....PR..',
        '.YPPOPY.',
        '....RG..',
        '........',
        '-......-',
      ],
      floor: [
        '-111111-',
        '........',
        '.11..11.',
        '.11..11.',
        '........',
        '........',
        '........',
        '11....11',
        '-1....1-',
      ],
      tutorial: [
        { do: 'swap', a: { c: 5, r: 5 }, b: { c: 4, r: 5 }, expect: { pw: 'x', c: 4, r: 5 }, text: 'Match in an L or T shape to build a Boombox.' },
        { do: 'tap', at: { c: 4, r: 5 }, text: 'Tap the Boombox to drop the bass!' },
      ],
    },
    {
      id: 5, name: 'Go Platinum', moves: 20, colors: [0, 2, 3, 4, 5],
      goals: [{ type: 'color', color: 5, count: 40 }, { type: 'color', color: 4, count: 34 }],
      intro: 'platinum',
      board: [
        '.---.---.',
        '..-...-..',
        '.........',
        '.........',
        '....G....',
        '...GYB...',
        '.BYYRYYG.',
        '....P....',
        '.........',
      ],
      tutorial: [
        { do: 'swap', a: { c: 4, r: 5 }, b: { c: 4, r: 6 }, expect: { pw: 'd', c: 4, r: 6 }, text: 'Line up 5 to go Platinum!' },
        { do: 'swap', a: { c: 4, r: 6 }, b: { c: 4, r: 7 }, text: 'Swap the Platinum Record with a cassette to clear every cassette.' },
      ],
    },

    // ---------------- Chapter 2: The Record Shop ----------------
    {
      id: 6, name: 'Crate Digging', moves: 15, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'crate' }],
      intro: 'crate',
      board: [
        '........',
        '........',
        '.1.11.1.',
        '1.1..1.1',
        '........',
        '........',
        '1.1..1.1',
        '.1.11.1.',
        '11....11',
      ],
    },
    {
      id: 7, name: 'Deep Crates', moves: 18, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'crate' }, { type: 'color', color: 1, count: 26 }],
      board: [
        '........',
        '........',
        '2......2',
        '.2....2.',
        '........',
        '...22...',
        '...22...',
        '........',
        '1.1..1.1',
      ],
    },
    {
      id: 8, name: 'Flyer Drop', moves: 21, colors: [0, 2, 3, 4, 5],
      goals: [{ type: 'crate' }, { type: 'color', color: 3, count: 26 }],
      intro: 'flyer',
      board: [
        '1.......1',
        '.........',
        '.........',
        '2.......2',
        '.........',
        '...YB....',
        '..RGGP...',
        '1.BGRGY.1',
        '21.BYP.12',
      ],
      tutorial: [
        { do: 'swap', a: { c: 5, r: 7 }, b: { c: 4, r: 7 }, expect: { pw: 'pl', c: 4, r: 7 }, text: 'Match 4 in a square to fold a Flyer.' },
        { do: 'tap', at: { c: 4, r: 7 }, text: 'Tap the Flyer. It flies straight to what you need.' },
      ],
    },
    {
      id: 9, name: 'Spin It Back', moves: 20, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'crate' }, { type: 'floor' }],
      board: [
        '---...---',
        '--.....--',
        '-.......-',
        '....2....',
        '...2.2...',
        '....2....',
        '-.......-',
        '--.....--',
        '---...---',
      ],
      floor: [
        '---111---',
        '--.....--',
        '-1.....1-',
        '11.....11',
        '1.......1',
        '11.....11',
        '-1.....1-',
        '--.....--',
        '---111---',
      ],
    },
    {
      id: 10, name: 'Baron Buzzkill', moves: 22, colors: [0, 1, 2, 3, 4], hard: 1,
      goals: [{ type: 'boss' }],
      boss: { kind: 'buzzkill', hp: 22, every: 4, attack: 'crate', count: 2 },
      intro: 'boss',
      board: [
        '...KK...',
        '...KK...',
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
      ],
    },

    // ---------------- Chapter 3: The Blacktop ----------------
    {
      id: 11, name: 'Taped Up', moves: 17, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'tape' }, { type: 'color', color: 0, count: 22 }],
      intro: 'tape',
      board: [
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
      ],
      tape: [
        'x......x',
        '.x....x.',
        '..x..x..',
        '...xx...',
        '...xx...',
        '..x..x..',
        '.x....x.',
        'x......x',
        '........',
      ],
    },
    {
      id: 12, name: 'Combo Moves', moves: 19, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'floor' }, { type: 'color', color: 4, count: 24 }],
      intro: 'combo',
      board: [
        '........',
        '........',
        '........',
        '........',
        '........',
        '...hv...',
        '........',
        '........',
        '........',
      ],
      floor: [
        '........',
        '..2222..',
        '.2....2.',
        '.2....2.',
        '.2....2.',
        '.2....2.',
        '.2....2.',
        '..2222..',
        '........',
      ],
      tutorial: [
        { do: 'swap', a: { c: 3, r: 5 }, b: { c: 4, r: 5 }, text: 'Swap two power-ups together for a combo!' },
      ],
    },
    {
      id: 13, name: 'Crown Run', moves: 22, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'crown' }],
      crowns: { total: 4, max: 1, gap: 3 },
      intro: 'crown',
      board: [
        '...C....',
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
        '........',
      ],
    },
    {
      id: 14, name: 'Cypher Circle', moves: 20, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'floor' }, { type: 'tape' }],
      board: [
        '--.....--',
        '-.......-',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
        '-.......-',
        '--.....--',
      ],
      floor: [
        '--11111--',
        '-1.....1-',
        '1..222..1',
        '1.2...2.1',
        '1.2...2.1',
        '1.2...2.1',
        '1..222..1',
        '-1.....1-',
        '--11111--',
      ],
      tape: [
        '.........',
        '.x.....x.',
        '.........',
        '...x.x...',
        '....x....',
        '...x.x...',
        '.........',
        '.x.....x.',
        '.........',
      ],
    },
    {
      id: 15, name: 'Windmill', moves: 22, colors: [0, 1, 2, 3, 4], hard: 1,
      goals: [{ type: 'crown' }, { type: 'crate' }],
      crowns: { total: 3, max: 1, gap: 3 },
      board: [
        '.........',
        '.........',
        '..1...1..',
        '...2.2...',
        '.........',
        '...2.2...',
        '..1...1..',
        '.........',
        '2.......2',
      ],
    },

    // ---------------- Chapter 4: The Wall ----------------
    {
      id: 16, name: 'Static Spreads', moves: 16, colors: [0, 1, 2, 3, 4], spread: true,
      goals: [{ type: 'static' }, { type: 'color', color: 3, count: 26 }],
      intro: 'static',
      board: [
        '........',
        '........',
        '........',
        '...SS...',
        '........',
        'S......S',
        '.S....S.',
        'S.S..S.S',
        '.S.SS.S.',
      ],
    },
    {
      id: 17, name: 'Triple Crates', moves: 19, colors: [0, 1, 2, 3, 4], spread: true,
      goals: [{ type: 'crate' }, { type: 'static' }],
      board: [
        '..3...3..',
        '.........',
        '3.......3',
        '.3.....3.',
        '3.......3',
        '....S....',
        '...S.S...',
        '....S....',
        '.........',
      ],
    },
    {
      id: 18, name: 'Paint the Wall', moves: 22, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'floor' }, { type: 'crate' }],
      board: [
        '.........',
        '.........',
        '.........',
        '1.1.1.1.1',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
      ],
      floor: [
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
        '222222222',
        '222222222',
        '222222222',
        '222222222',
      ],
    },
    {
      id: 19, name: 'Crown Heist', moves: 23, colors: [0, 1, 2, 3, 4], spread: true,
      goals: [{ type: 'crown' }],
      crowns: { total: 5, max: 2, gap: 2 },
      board: [
        '.........',
        '.........',
        '.........',
        'S.......S',
        'S.......S',
        '.........',
        '.........',
        '.........',
        '.........',
      ],
    },
    {
      id: 20, name: 'Lady Lip-Sync', moves: 24, colors: [0, 1, 2, 3, 4], hard: 1,
      goals: [{ type: 'boss' }],
      boss: { kind: 'lipsync', hp: 32, every: 3, attack: 'tape', count: 3 },
      board: [
        '...KKK...',
        '...KKK...',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
      ],
    },

    // ---------------- Chapter 5: The Crown Arena ----------------
    {
      id: 21, name: 'Arena Gates', moves: 23, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'crate' }, { type: 'floor' }],
      board: [
        '.........',
        '.........',
        '.........',
        '3.2...2.3',
        '.........',
        '.........',
        '.........',
        '.........',
        '2.......2',
        '32.....23',
      ],
      floor: [
        '.........',
        '.........',
        '.........',
        '.........',
        '.2222222.',
        '.2222222.',
        '.1111111.',
        '.1111111.',
        '.........',
        '.........',
      ],
    },
    {
      id: 22, name: 'Mixtape Maze', moves: 28, colors: [0, 1, 2, 3, 4],
      goals: [{ type: 'crown' }, { type: 'color', color: 4, count: 24 }],
      crowns: { total: 3, max: 1, gap: 3 },
      board: [
        '.........',
        '.........',
        '.........',
        '..--.--..',
        '..--.--..',
        '.........',
        '.........',
        '.........',
        '-.......-',
      ],
    },
    {
      id: 23, name: 'Static Storm', moves: 17, colors: [0, 1, 2, 3, 4], spread: true,
      goals: [{ type: 'static' }, { type: 'floor' }],
      board: [
        '.........',
        '.........',
        '.........',
        '.........',
        'S.......S',
        '.S.....S.',
        'S.S...S.S',
        '.S.S.S.S.',
        'S.S...S.S',
      ],
      floor: [
        '.........',
        '.2222222.',
        '.2222222.',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
      ],
    },
    {
      id: 24, name: 'All Elements', moves: 22, colors: [0, 1, 2, 3, 4], hard: 2,
      goals: [{ type: 'crown' }, { type: 'floor' }, { type: 'crate' }],
      crowns: { total: 3, max: 1, gap: 3 },
      board: [
        '.........',
        '.........',
        '2.......2',
        '.........',
        '...1.1...',
        '.........',
        '.........',
        '.........',
        '1.......1',
        '21.....12',
      ],
      floor: [
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
        '..22222..',
        '..22222..',
        '.........',
        '.........',
        '.........',
      ],
      tape: [
        '.........',
        '.........',
        '.........',
        '.x.....x.',
        '.........',
        '.........',
        '.........',
        '.x.....x.',
        '.........',
        '.........',
      ],
    },
    {
      id: 25, name: 'King Static', moves: 27, colors: [0, 1, 2, 3, 4], hard: 2, spread: true,
      goals: [{ type: 'boss' }],
      boss: { kind: 'static', hp: 44, every: 3, attack: 'static', count: 2 },
      board: [
        '...KKK...',
        '...KKK...',
        '...KKK...',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
        '.........',
      ],
    },
  ];

  return { LEVELS };
});
